// <auto-generated />
using System;
using Entity.Pedidos.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity.Pedidos.Data.Migrations
{
    [DbContext(typeof(PedidosDbContexto))]
    partial class PedidosDbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasCharSet("utf8mb4")
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.CupomDesconto", b =>
                {
                    b.Property<int>("CupomDescontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aplicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AplicadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoCupom")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PercentualDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TipoCupomDesconto")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CupomDescontoId");

                    b.ToTable("CupomDescontos");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("enderecos", t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<int?>("CupomDescontoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int")
                        .HasColumnName("endereco_id");

                    b.Property<int>("PedidoStatus")
                        .HasColumnType("int");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double")
                        .HasColumnName("valor_total");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CupomDescontoId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_pedidos_cliente_id");

                    b.HasIndex(new[] { "EnderecoId" }, "IX_pedidos_endereco_id");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.PedidoItem", b =>
                {
                    b.Property<int>("PedidoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("longtext");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PedidoItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.Pedido", b =>
                {
                    b.HasOne("Entity.Pedidos.Domain.Entidades.CupomDesconto", "CupomDesconto")
                        .WithMany("Pedidos")
                        .HasForeignKey("CupomDescontoId");

                    b.HasOne("Entity.Pedidos.Domain.Entidades.Endereco", "Endereco")
                        .WithMany("Pedidos")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CupomDesconto");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.PedidoItem", b =>
                {
                    b.HasOne("Entity.Pedidos.Domain.Entidades.Pedido", "Pedido")
                        .WithMany("PedidoItens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.CupomDesconto", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.Endereco", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Entity.Pedidos.Domain.Entidades.Pedido", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
